# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
# name: Build and deploy

name: build_and_deploy

on:
  release:
    types: [created]

jobs:
  deploy_cratesio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: setup cargo
      run: |
        cargo login ${{ secrets.CARGO_TOKEN }}
        cargo package
        cargo publish

  deploy_pypi_manylinux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build Manylinux Maturin
      uses: ./.build_action/
      id: maturin
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: pypi-${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload target/wheels/*


