# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
# name: Build and deploy

name: build_and_deploy

on:
  release:
    types: [created]

jobs:
  deploy_cratesio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: setup cargo
      run: |
        cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
        cargo publish

  deploy_pypi_manylinux:

      runs-on: ubuntu-latest
      #container: konstin2/maturin
      steps:
      - uses: actions/checkout@v2
      - name: Build Manylinux Maturin
        uses: addnab/docker-run-action@v1
        with:
          image: konstin2/maturin
          options: -v /home/runner/work/qoqo_calculator_pyo3/qoqo_calculator_pyo3:/io
          run: maturin build --release --manylinux 2010
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: pypi-${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install twine
          twine upload target/wheels/*


